name: DAST - ZAP Spider (localhost)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap_spider_local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: |
          test -f gradlew && chmod +x gradlew || true
          sed -i 's/\r$//' gradlew || true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build & start app (localhost:8080)
        run: |
          bash ./gradlew bootJar -x test
          JAR=$(ls build/libs/*.jar | head -n1)
          nohup java -jar "$JAR" --server.port=8080 --server.address=0.0.0.0 > /tmp/app.log 2>&1 &
          for i in {1..60}; do
            curl -sf http://127.0.0.1:8080/v1/products && break
            sleep 2
          done

      - name: ZAP Baseline (Spider básico)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://host.docker.internal:8080/v1/products'  # acessa o host a partir do container
          cmd_options: >-
            -m 2
            -r zap-baseline.html
          allow_issue_writing: false
          artifact_name: zap_spider_baseline
