name: SAST - Semgrep (Kotlin/Spring) - OSS

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep scan (OSS rules) -> SARIF
        uses: returntocorp/semgrep-action@v1
        with:
          entryPoint: scan
          # Gere o SARIF diretamente
          args: >-
            --config p/owasp-top-ten
            --config p/secrets
            --config p/java
            --config p/kotlin
            --config p/spring
            --sarif
            --output semgrep.sarif
            --metrics=off
          # NÃO defina SEMGREP_APP_TOKEN aqui

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
