name: SAST - Semgrep (Cloud Policy)

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # publicar SARIF na aba Security
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Gera SARIF a partir da POLICY do Semgrep Cloud
      #    (precisa do token para baixar a policy)
      - name: Semgrep scan (policy -> SARIF)
        uses: returntocorp/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        with:
          entryPoint: semgrep
          args: >-
            scan
            --config=policy
            --sarif
            --output=semgrep.sarif
            --metrics=off

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      # 2) Aplica o gate da sua POLICY (bloqueia PR conforme severidade definida lรก)
      - name: Semgrep CI (enforce Cloud Policy)
        uses: returntocorp/semgrep-action@v1
        with:
          entryPoint: ci
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
