name: SCA - OWASP Dependency-Check (Docker)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "CI-CD" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  odc:
    runs-on: ubuntu-latest
    env:
      DC_FAIL_ON_CVSS: "7.0" # falha com High/Critical
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ FIX: usar ${{ }} no hashFiles
      - name: Restore ODC data cache
        uses: actions/cache@v4
        with:
          path: ./.odc-data
          key: odc-data-v11-${{ runner.os }}-${{ hashFiles('**/build.gradle*','**/pom.xml','**/package-lock.json','**/gradle.lockfile','**/gradle/**') }}
          restore-keys: |
            odc-data-v11-${{ runner.os }}-

      - name: Prep dirs de trabalho
        run: |
          mkdir -p .odc-data odc-reports

      - name: Dependency-Check (Docker)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker pull owasp/dependency-check:latest

          SUPP=""
          if [ -f security/dependency-check-suppression.xml ]; then
            SUPP="--suppression /src/security/dependency-check-suppression.xml"
          fi

          # roda como o mesmo UID/GID p/ evitar permissão  (gera HTML/JSON/SARIF)
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -e NVD_API_KEY="$NVD_API_KEY" \
            -v "$PWD":/src \
            -v "$PWD/.odc-data":/usr/share/dependency-check/data \
            -v "$PWD/odc-reports":/report \
            owasp/dependency-check:latest \
            --scan /src \
            --project "${{ github.repository }}@${{ github.sha }}" \
            --out /report \
            --format HTML --format JSON --format SARIF \
            --failOnCVSS "${DC_FAIL_ON_CVSS}" $SUPP || true

          echo "Arquivos gerados:"
          ls -lah odc-reports || true

      # ✅ Só faz upload se o SARIF existir
      - name: Upload SARIF para o GitHub
        if: always() && hashFiles('odc-reports/dependency-check-report.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: odc-reports/dependency-check-report.sarif
          category: owasp-dependency-check

      - name: Upload artifacts (HTML/JSON/SARIF)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: odc-reports
          path: |
            odc-reports/dependency-check-report.html
            odc-reports/dependency-check-report.json
            odc-reports/dependency-check-report.sarif
          if-no-files-found: warn
